import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b px-6 py-4 flex gap-6">
          <a href="/overview" className="font-semibold">LifeOps</a>
          <a href="/overview" className="text-sm text-gray-600">Overview</a>
          <a href="/tasks" className="text-sm text-gray-600">Tasks</a>
          <a href="/documents" className="text-sm text-gray-600">Documents</a>
          <a href="/upload" className="text-sm text-gray-600">Upload</a>
          <a href="/approvals" className="text-sm text-gray-600">Approvals</a>
          <a href="/activity" className="text-sm text-gray-600">Activity</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
